The pre-push githook (quality check, seems unused) is now disabled by default, unless setting env var ENABLE_QC

diff --git a/.githooks/pre-push b/.githooks/pre-push
--- a/.githooks/pre-push
+++ b/.githooks/pre-push
@@ -6,17 +6,15 @@
 remote="$1"
 url="$2"
 
-# This hook makes sure that when we push to a branch the code is ready for a pull request
-# It is possible to skip this (for debug/as needed) by setting the environment variable
-# 'SKIP_CI`. Make sure to use this options only when absolutely needed.
+# This hook makes sure that when we push to a branch the code quality is ready for a pull request.
+# This quality check is skipped by default, unless you set the env var 'ENABLE_QC'. 
 echo "========> Executing make ci_pull_request to make sure that this push is ready for PR"
 
-if [ "$SKIP_CI" ]; then
-    echo "========> SKIP_CI is set. Skipping CI check."
+if [ -n "$ENABLE_QC" ]; then
+    make ci_pull_request && echo "========> Done." || { echo "========> Failed."; exit 1; }
     exit 0
-fi
+fi    
 
-make ci_pull_request && echo "========> Done." || { echo "========> Failed."; exit 1; }
-
+echo "========> ENABLE_QC is not set. Skipping quality check."
 
 exit 0
